### ISSUE TITLE
invalid install rule is breaking debian builds

### ISSUE THREAD

**Issue by tfoote** [aau-ros/aau_multi_robot#1]
```
/share/adhoc_communication/package.xml
CMake Error at cmake_install.cmake:115 (FILE):
  file INSTALL cannot find
  "/tmp/buildd/ros-hydro-adhoc-communication-0.1.3-4precise-20150202-0726/simulation_5.launch".
```

from: http://jenkins.ros.org/view/HbinP64/job/ros-hydro-adhoc-communication_binarydeb_precise_amd64/198/consoleFull

It looks like the launch file was pushed into a subdirectory but the install rule was not updated appropriately: https://github.com/aau-ros/aau_multi_robot/blob/master/adhoc_communication/CMakeLists.txt#L205

**Comment by tfoote** [comment]
This is breaking a downstream package rosjava_messages http://lists.ros.org/pipermail/ros-release/2015-February/004572.html

**Comment by aau-ros** [comment]
This issue should be resolved. If problems still occur, please let us know.
