### ISSUE TITLE
Do you have a Wiki??

### ISSUE THREAD

**Issue by KeoChi** [aau-ros/aau_multi_robot#11]
Hello!I have a turtlebot and I want it to explore a room.But I don't how to use your package ! For example, i don't know what the "robot_prefix" should be.  Can you give me A detailed tutorial?Thank you!

**Comment by aau-ros** [comment]
You can find the wiki page in the ROS wiki: http://wiki.ros.org/explorer
Unfortunately at the moment we don't have any tutorials.

Regarding the robot prefix:
If you do simulations with multiple robots, the prefix defines the namespace of the explorer. It needs to be different for each instance of the explorer. If you run the explorer just once (either single robot simulation or physical experiment) it can be left empty.

**Comment by KeoChi** [comment]
Amazing! It works! Thank you! But I don't know the mean of the black round in the rviz.
