### ISSUE TITLE
Release into ROS Indigo?

### ISSUE THREAD

**Issue by 130s** [aau-ros/aau_multi_robot#3]
This tool looks awesome. Is there any reason that hesitates you from releasing into newer, long-term support ROS distro?
If the issue is "time", I can help you out for the release chores ;)

**Comment by aau-ros** [comment]
We are working on a release. Currently OpenCV is giving us troubles.

**Comment by aau-ros** [comment]
Its done: https://github.com/ros/rosdistro/pull/8843
